### ISSUE TITLE
nfs3 plugin is incorrect

### ISSUE THREAD

**Issue by eccles** [dagwieers/dstat#10]
The nfs3 plugin calculates a 'readdir' statistic which is the sum of fields 17 and 18 in /proc/net/rpc/nfs. However comparing the contents of this file with the output of the 'nfsstat' command shows that 'readdir' should be fields 18+19. Also the 'filesystem value should be fields 20+21+22 (not 19+20+21) and the 'commit'' value should be field 23 and not 22

```
# cat /proc/net/rpc/nfs
net 0 0 0 0
rpc 3753467 0 0
proc2 18 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
proc3 22 0 1602112 28201 101419 220208 27 493468 1108826 84987 4140 4 0 62226 1112 2682 6 0 2003 41991 52 0 0
proc4 36 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
# cat /proc/net/rpc/nfs;nfsstat -c -3
net 0 0 0 0
rpc 3753827 0 0
proc2 18 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
proc3 22 0 1602333 28201 101451 220238 27 493468 1108848 85009 4140 4 0 62248 1112 2682 6 0 2003 42002 52 0 0
proc4 36 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Client rpc stats:
calls      retrans    authrefrsh
3753827    0          0       

Client nfs v3:
null         getattr      setattr      lookup       access       readlink     
0         0% 1602333  42% 28201     0% 101451    2% 220238    5% 27        0% 
read         write        create       mkdir        symlink      mknod        
493468   13% 1108848  29% 85009     2% 4140      0% 4         0% 0         0% 
remove       rmdir        rename       link         readdir      readdirplus  
62248     1% 1112      0% 2682      0% 6         0% 0         0% 2003      0% 
fsstat       fsinfo       pathconf     commit       
42002     1% 52        0% 0         0% 0         0% 
```

**Comment by petef4** [comment]
I came here to report this same bug. I would add to eccles' report that field 17 (link) should be added into 'inode'. On a separate point ought 'inode' be renamed to 'other'?

The source code nfsstat.c uses this to parse /proc/net/rpc/nfs

```c
static const char *	nfsv3name[SRVPROC3_SZ] = {
	"null",   "getattr", "setattr",  "lookup", "access",  "readlink",
	"read",   "write",   "create",   "mkdir",  "symlink", "mknod",
	"remove", "rmdir",   "rename",   "link",   "readdir", "readdirplus",
	"fsstat", "fsinfo",  "pathconf", "commit"
};
```

**Comment by scottchiefbaker** [comment]
If someone wants to send us a pull request with this fixed I'd be happy to get this merged.

**Comment by petef4** [comment]
I'll see if I can manage that tomorrow (2016-03-16). I've been running a locally patched version since reporting it. I will drop the "experimental" warning too if that is okay.

Kudos for getting dstat active again.

**Comment by scottchiefbaker** [comment]
@petef4 the last change on this file was 2012. If you've been using it for a while and haven't encountered any other major issues, and are willing to fix this issue I'm fine with removing the experimental flag.

Thanks for your help.

**Comment by scottchiefbaker** [comment]
Merged... closing issue
