### ISSUE TITLE
RFE - Ability to exclude a class of disk devices from the aggregate disk read/write totals - SDx/TDMPx for example

### ISSUE THREAD

**Issue by nexus2** [dagwieers/dstat#103]
Great tool!

Ability to exclude a class of disk devices from the aggregate disk/io read/write totals.

Ability to exclude either all SDx devices or TDMPx devices from the aggregate total.

Thanks!

**Comment by nexus2** [comment]
We modified the following line in /usr/bin/dstat to examine only TDMPx devices
for disk/io/total
:
        self.diskfilter = re.compile('^(dm-\d+|md\d+|sd[a-z]+|sd[a-z]+\d+|tdmp[a-z]+\d+)$')

Thanks!

**Comment by scottchiefbaker** [comment]
How would you want this to look? Do you want a exclude pattern (blacklist) that would match certain types of disks. 

You can already specify which disks to include with `-D` if you only want to see specific ones.

**Comment by carsten-AEI** [comment]
I know this is a very old RFE and I'm not sure if development is still underway, but a typical use case would be a server with zpools.

Each zpool is represented by a device (`/dev/zd*`) and if you run dstat in simply disk summary mode it will double count disk accesses (single underlying disk drives plus zfs device which already sums the single disk drives). Given that large servers can often have 20-60 drives per server in multiple zpools using the `-D` switch is not really straightforward without additional wrapper scripts.

Thus, a blacklist option would be much appreciated.
