### ISSUE TITLE
Planning for the new release of dstat

### ISSUE THREAD

**Issue by scottchiefbaker** [dagwieers/dstat#104]
Paging: @svenstaro, @dagwieers, @thinrope, @SpamapS, @kdave

First and foremost I'd like to thank @dagwieers for opening up dstat and letting the community help. Dstat is too important a project to wither away. :+1: :+1: :+1: 

We decided to close down #55 to re-focus our efforts on a new release without all the > 2+ year old cruft on that old issue. I'd like to start planning what people would like to see in a new release. Here are my suggestions

1. Release early, release often. It won't be perfect, but we should let people know the project isn't dead
  1. Do we want to establish a consistent release schedule?
1. Update documentation to reflect any changes in commits since last release
1. Any low hanging fruit among the existing pull-requests we can pull in?
  1. Or should we just release what we have in git already without pulling in new code
1. Do we want to establish a Github "organization" for dstat that we can have all support? Or do we leave it where it is?
1. Are there any known bugs that we should address right away?
1. Anything else at all?

I'll be the first to admit my Python skills are severely lacking (I'm a Perl guy), so I may not be able to contribute any whiz-bang code, but I can help coordinate.

#longlivedstat

**Comment by scottchiefbaker** [comment]
It looks like 5251397 was the 0.7.2 release. Anyone know want to come up with a changelog between there and now? I know my `--bits` fix is in there, but I'm not sure what else.

**Comment by kdave** [comment]
See the ChangeLog file.

**Comment by kdave** [comment]
All the interesting changes seem to be there.

**Comment by kdave** [comment]
Pull requests #60 and #95 seem to be good candidates for the upcomming release. There are several lustre fixes that would need more time to see how much they overlap, the rest seem to be feature request.
Issue #5 seems to be easy to fix.
My suggestion: merge/fix those and ship 0.7.3
The next releases could be from the 0.7.x line, merging pending PRs and fixing easy bugs first, on a monthly basis. As this is a tool intended for humans, we don't need to worry much about changes in the interface, so the relatively fast pace should be ok.
The 0.8.x schedule could address the larger features or internal rewrites, and can go in parallel with 0.7 anyway.

**Comment by scottchiefbaker** [comment]
I like making the next release 0.7.3. Anyone think it should be something different? 

I'd like to get that release out the door, and then create a `next` branch as well as our existing `master` branch. That way `master` will (almost always) be the latest stable release, and `next` can be "beta" until we officially make another release. Any thoughts on this git methodology?

**Comment by dagwieers** [comment]
No, it should definitely be 0.7.3.

**Comment by dagwieers** [comment]
I wouldn't bother having multiple branches, unless a complete rewrite is planned.

**Comment by scottchiefbaker** [comment]
@kdave I don't know enough Python to understand what's going on in #60. If you say it's good, that's fine with me though. @dagwieers thoughts?

#95 seems like a no brainer, that we can merge no problem. @dagwieers do you want me to handle those pull requests? Should we come to a group consensus on pull requests and then land them? How would you like that process to work. I do **not** want you to feel like we're "taking over" dstat. I want this to be a community effort.

Issue #5 doesn't exist, so I'm a little confused there.

**Comment by scottchiefbaker** [comment]
Just to clarify my thoughts for the "release process"... Github does a good job of creating releases from tags. I went ahead and created a tag for `dstat-0.7.2` for historical purposes. I used the commit message @dagwieers used in 2010 to find that. I think we can just tag whatever commit we want with the appropriate version and let github handle the rest. @dagwieers can then post those .tar.gz on his website, or update that website to point at github. Totally up to you.

https://github.com/dagwieers/dstat/releases

**Comment by dagwieers** [comment]
@scottchiefbaker You can already start tagging the PRs (and issues) you want to pull to the correct milestone. E.g. if you want to release ASAP, you may want to move the open issues to a new milestone 0.7.4.

We should also go over the reported issues and see which ones are valid (bug/feature), which only requires support, or which ones need feedback, or are invalid. The bugs and features can then also be put into milestones.

Released tarballs are actual tarballs created using `make dist`. Since those tarballs usually include converted man-pages, etc.

**Comment by dagwieers** [comment]
I have been doing some triage, and move some stuff to milestone 0.7.3 and 0.7.4.
Some PRs need feedback, some issues need feedback.

Some of the PRs I was reluctant to merge, since I don't use the software I cannot validate whether it fixes, or breaks something. The thermal stuff is one of those things that is easy to get right for you, but wrong for others... Usually I request information from /proc and collect and compare files. Things tend to change with kernel releases :-/

You can see the milestones here:
https://github.com/dagwieers/dstat/milestones

Feel free to reorganize.

**Comment by scottchiefbaker** [comment]
Oh cool, I've never used milestones before I'll check it out. I may end up moving a lot of these to 0.7.4 just to get a "clean" release out the door. Rather than a mad rush to try and merge stuff that no one has looked at it in 2+ years.

**Comment by dagwieers** [comment]
@scottchiefbaker Sure, that's your prerogative ;-) I don't disagree as that's my problem every time I wanted to do a perfect release.

**Comment by dagwieers** [comment]
Already some great results. New labels. Milestones are clearer. Triaging.
I need some sleep now, thrilled to see what tomorrow brings !

**Comment by kdave** [comment]
@scottchiefbaker I meant issue #10, sorry

**Comment by scottchiefbaker** [comment]
@kdave no worries. I went ahead and flagged that with a target of 0.7.3. We just need a pull request to fix that. If you want to work on that, we can get this release out the door pretty quick.

**Comment by scottchiefbaker** [comment]
:smile::star2::smile::star2::smile::star2::smile::star2::smile::star2::smile:

I think we're ready for an actual release! I was able to merge in the last couple hold-outs before 0.7.3. I think we're in really **good** shape for a release. It probably won't be perfect, but I expect 0.7.4 to come hot on the heels of this release to address any issues. Once we get an official release out the door I think we'll get more feedback from users as well.

@dagwieers if you're good I'd like to tag this release 0.7.3 and get it out the door. Then you're welcome to update your site with the appropriate .tar.gz.

What do you guys think?

#releaseearlyreleaseoften

**Comment by kdave** [comment]
Go go go!

**Comment by scottchiefbaker** [comment]
@kdave I emailed @dagwieers and he said he's busy today/tonight but might have time tomorrow to work on the official release. That said, how do *you* feel about what we have so far? Are we in good shape for a release? The more feedback we get the better I'll feel.

**Comment by dagwieers** [comment]
I just found out that `make dist` no longer works because it relies on svn (subversion).
So this proves I never made a release after I moved the project to Github. Sigh ;-)

**Comment by scottchiefbaker** [comment]
Ok it's official. 0.7.3 is tagged and "released"

https://github.com/dagwieers/dstat/releases

**Comment by kdave** [comment]
Btw, naming the tag as dstat-0.7.3 generates the tarball with path dstat-dstat-0.7.3, usually it's just v0.7.3 or plain 0.7.3 .

**Comment by dagwieers** [comment]
@kdave Aha, this was done previously because the tarball would have a directory **0.7.2/** instead of **dstat-0.7.2**. But I noticed that has been fixed in the meantime. I guess we should be tagging them by just the number them. Thanks for reporting !
