### ISSUE TITLE
Bump the version number in dstat to 0.7.3

### ISSUE THREAD

**Issue by scottchiefbaker** [dagwieers/dstat#105]
Line 26 of dstat includes the version number. We'll need to bump that to whatever is appropriate. This is a note to talk to @dagwieers about how that part works.

**Comment by scottchiefbaker** [comment]
@dagwieers I think I understand how that works now. Looks like I just need to change VERSION to "0.7.3", as the only place that uses that is the Makefile? I landed ab123c69682c27621f9e24adfd67ecc6792f8656 to address this new version number. Once we release 0.7.3 we can bump this file to `0.7.4-git` and start work on that.

**Comment by dagwieers** [comment]
Looks fine to me.
