### ISSUE TITLE
Need a way to pass information in to a plugin

### ISSUE THREAD

**Issue by scottchiefbaker** [dagwieers/dstat#107]
Currently the only way to get information from the CLI in to a plugin is with:
1. Environment variables
2. Hijacking existing options

Neither of these are optimal. We need to establish a better way of getting data from the CLI in to a plugin that's intuitive for the user. Ideally it would look something like this

```
# No data sent to myplugin
dstat --time --myplugin --load
```

```
# "foo,bar,baz" sent to myplugin
dstat --time --myplugin foo,bar,baz --load
```

**Comment by scottchiefbaker** [comment]
Blocking #97

**Comment by scottchiefbaker** [comment]
Blocking #93 also

**Comment by scottchiefbaker** [comment]
It would be handy inside of a plugin for the plugin to be aware of it's own name also. The following code will check ARGV for options and extract what was specified (in this case after `--freespace`) 

    def get_plugin_options(self):
        count = 0
        total = len(sys.argv)
        ret   = []
        found = []

        # Loop through each arg looking for --freespace
        for arg in sys.argv:
            count += 1
            is_last = (count == total)

            # If we find --freespace check if the next arg is data (not another option)
            if (arg == '--freespace') and (not is_last):
                next = sys.argv[count]

                # If the next arg does *not* start with "-" (i.e. it's not an another option)
                # Note: will break if the next item is a negative number like -9
                if next[:1] != "-":
                    found = next.split(',')

        #print "Found: " + ", ".join(ret)
        return ret

If the plugin knows it's own name we could change that check for `--freespace` to `'--' + plugin_name` and make it more dynamic.

**Comment by dagwieers** [comment]
Not sure if this is the right approach. I'd rather look into a plugin mechanism where plugins report which additional options they provide, and which dstat takes into account.

The obvious problem is the overlap/conflicting use of the same option between plugins. Which is something we can only manage ourselves to avoid abuse.

**Comment by dagwieers** [comment]
I would like to propose another solution:

    `--freespace --opts=/,/usr --plugin2 --opts=1,2,3`

But this means that the order of the options is important, at least for `--opts=`, the order of the plugins already influences the order of shown counters, so the order has some meaning now already. 

The interface could be enhanced if more than one piece of information is required.

    `dstat --mysql5-conn --opts="user=foobar password=1234"`

Harder to parse, but less screen-bloat than:

    DSTAT_MYSQL_USER=foobar DSTAT_MYSQL_PWD=1234 dstat --mysql5-conn

How this information can be reused for multiple plugins is the question. In this case if you provide more than one mysql plugin, you probably want to use the same settings again. Or you may wish to override it.

Maybe we should turn it around:

    `dstat --opts="server=1.2.3.4 user=foobar password=1234" --mysql5-conn --mysql5-innodb`

But if you'd be doing a second connection to a different server:

    `dstat --opts="server=1.2.3.4 user=foobar password=1234" --mysql5-conn --opts="server=1.2.3.5" --mysql5-conn`

The implementation would be parsing --opts, and merging/updating the information in a dictionary that is being provided to each individual plugin based on the order.

**Comment by scottchiefbaker** [comment]
I still like my original solution best. It's the most "unixy" as your passing parameters in to `--freespace`, instead of a separate `--opts` call. In the code above the data immediately following a `--option` is checked to see if it's another option (i.e. `-a` or `--append`), if it's determined that it's *not* the next option it's read as the parameters for the current option. It works quite well.

**Comment by Dagrut** [comment]
Hi!

Just an idea about this : why not allowing "=" signs optionally?
Like allowing `--freespace` or `--freespace=/,/var`
This may (might?) also be extended to base plugins, lile `-d=sda,sdb`

**Comment by scottchiefbaker** [comment]
I'd like to modify a couple of plugins to expand functionality, but not having a clear method to pass data to them is complicating things. Where are we at on this @dagwieers ?
