### ISSUE TITLE
Enable Travis, PR/issue templates and checksums

### ISSUE THREAD

**Issue by dagwieers** [dagwieers/dstat#109]
To help us with the release process there are 3 things we can do:

 - Add Github templates for PRs and issues, so that people provides us with as much information as possible. (people tend to be lazy, Dstat users more so ;-))

 - Enable Travis with the following default tests:
    - Test the codebase with python 2.6 (RHEL6) and python 3.X
    - Test a 10 sec dstat run (without plugins)
    - For each plugin, do a 10 sec test with each individual plugin enabled
    - Also enable logging to test those codepaths

 - Add release checksums (md5, sha1, sha256) to GitHub for people to compare against
   (Need to check if there is a standard filename for this already)

**Comment by dagwieers** [comment]
GitHub templates have been implemented.
Travis support is implemented.

I still need to find out if there is a standard for release checksums (e.g. to assist automated validation).

**Comment by scottchiefbaker** [comment]
Good work! You've been busy...

**Comment by scottchiefbaker** [comment]
What's left before we make a final release? I'm really excited to get this out the door.

**Comment by dagwieers** [comment]
I think we can do a release just the way it is now. I can make a tarball using 'make dist' from the release you have tagged. And usually I update site like freshmeat (which no longer exists, and I don't know an alternative), slashdot, LWN, etc...

Especially now that it has been almost 6 years since the previous release, it can't hurt to make people aware.

**Comment by scottchiefbaker** [comment]
If you're OK with it I'll tag ebace6d4177f8748f35cec87f7a49946046b0a20 as 0.7.3 and we'll make that the official release. Then you can update wherever you need to.

**Comment by dagwieers** [comment]
Fine by me.

**Comment by scottchiefbaker** [comment]
ebace6d4177f8748f35cec87f7a49946046b0a20 is officially 0.7.3. Good job team!

**Comment by dagwieers** [comment]
Shall we enable the Wiki and document the release process on the Wiki ?

I think we should do some basic tests to look for memory leaks in plugins (dstat --dstat-mem).
But we should also document how to tag releases, how to promote the release publicly, writing the release changelog, bug-triage, etc... And then refine it with every passing release.
