### ISSUE TITLE
Move Dstat website to GitHub pages

### ISSUE THREAD

**Issue by dagwieers** [dagwieers/dstat#110]
##### SUMMARY

It would be better if the Dstat website is managed by the community.
We could enable the GitHub Wiki site, but I don't like it that much.
Have a full-fledged Dstat website from GitHub would be preferred.
##### ISSUE TYPE

- Documentation report

**Comment by abitrolly** [comment]
Also, Fedora package link is broken. The correct one is now https://apps.fedoraproject.org/packages/dstat

And links to blog posts are also need to be refreshed.
