### ISSUE TITLE
Update dag.wiee.rs to reflect the new release

### ISSUE THREAD

**Issue by scottchiefbaker** [dagwieers/dstat#112]
@dagwieers do you have plans to update/revamp http://dag.wiee.rs/home-made/dstat/ to reflect the new release? That site is currently pretty high up on Google when you search for `dstat` so I imagine it's generating confusion.

**Comment by dagwieers** [comment]
Yes, that's why I opened #110 ?

**Comment by scottchiefbaker** [comment]
#110 targets 0.7.4. Can you just change the link to point at the .tar.gz for 0.7.3 until we have time to address #110.

**Comment by dagwieers** [comment]
Well, now that 0.7.3 is out, nothing is stopping us from doing it right now. We don't have to wait for a 0.7.4 release to close all tickets (in fact, that would be bad strategy anyhow). But sure, I can update the website. It will not bring us closer to closing #110, it's ony relieving pressure ;-)
