### ISSUE TITLE
Column headers not showing up when needed

### ISSUE THREAD

**Issue by raedah** [dagwieers/dstat#116]
Running dstat with a delay time of 600. Headers never appear again after they scroll off the screen, making it difficult to know what the columns are. I paged up through 3 pages and confirmed that the headers were only displayed at the apps start and thats it.

Also noticed when testing, that even with the default delay of 1, the headers disappear off the top before they are again written at the bottom, so there is an interval where there are no headers displaying at all.

**Comment by dagwieers** [comment]
I cannot reproduce this. It works correctly in both occasions for me.
Please provide me with the output of `dstat --version`.

**Comment by raedah** [comment]
$ dstat --version
Dstat 0.7.3
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/dstat/

Platform posix/linux2
Kernel 4.5.2-1-ARCH
Python 2.7.11 (default, Mar 31 2016, 06:18:34) 
[GCC 5.3.0]

Terminal type: xterm-256color (color support)
Terminal size: 43 lines, 132 columns

Processors: 4
Pagesize: 4096
Clock ticks per secs: 100

internal:
	aio, cpu, cpu-adv, cpu-use, cpu24, disk, disk24, disk24-old, epoch, fs, int, int24, io, ipc, load, lock, mem, mem-adv, 
	net, page, page24, proc, raw, socket, swap, swap-old, sys, tcp, time, udp, unix, vm, vm-adv, zones
/usr/share/dstat:
	battery, battery-remain, condor-queue, cpufreq, dbus, disk-avgqu, disk-avgrq, disk-svctm, disk-tps, disk-util, disk-wait, 
	dstat, dstat-cpu, dstat-ctxt, dstat-mem, fan, freespace, fuse, gpfs, gpfs-ops, helloworld, innodb-buffer, innodb-io, 
	innodb-ops, lustre, md-status, memcache-hits, mysql-io, mysql-keys, mysql5-cmds, mysql5-conn, mysql5-innodb, 
	mysql5-innodb-basic, mysql5-innodb-extra, mysql5-io, mysql5-keys, net-packets, nfs3, nfs3-ops, nfsd3, nfsd3-ops, 
	nfsd4-ops, nfsstat4, ntp, postfix, power, proc-count, qmail, redis, rpc, rpcd, sendmail, snmp-cpu, snmp-load, snmp-mem, 
	snmp-net, snmp-net-err, snmp-sys, snooze, squid, test, thermal, top-bio, top-bio-adv, top-childwait, top-cpu, top-cpu-adv, 
	top-cputime, top-cputime-avg, top-int, top-io, top-io-adv, top-latency, top-latency-avg, top-mem, top-oom, utmp, vm-cpu, 
	vm-mem, vm-mem-adv, vmk-hba, vmk-int, vmk-nic, vz-cpu, vz-io, vz-ubc, wifi, zfs-arc, zfs-l2arc, zfs-zil

**Comment by raedah** [comment]
Running dstat with a delay time of 600, takes 10 minutes to generate a line, and so approx 4 hours to run off the top of the screen, so given your response 2 minutes after I filed the bug, I have doubts that you waited 4 hours.

**Comment by dagwieers** [comment]
Ah, so you think this bug only manifests if you specify 600 ?
That would be a rather strange bug.
There is no real difference between `dstat 2` and `dstat 600`, and you also did not specify the number of lines your terminal was having. (And BTW the number of lines do influence the display of headers)

**Comment by dagwieers** [comment]
BTW Do you happen to use any of the following options: `--noheader` or `--noupdate`.
Because both these options do no repeat the header...

**Comment by raedah** [comment]
I am using --noupdate, but even with that headers appear and repeat with the default delay of 1. In my test, the lack of repeating headers only occurs with the large 600 delay.  The number of rows in my terminal is 43.

**Comment by raedah** [comment]
I just tested this with a 60 second delay and had the same result. Header did not repeat. Repeats just fine with the default one second delay though.

**Comment by raedah** [comment]
dstat --noupdate 2
You should be able to duplicate it with that. It requires a delay setting above 1, and --noupdate.
