### ISSUE TITLE
Missing option to enable cpu_adv stats

### ISSUE THREAD

**Issue by ghost** [dagwieers/dstat#119]
The advanced cpu statistics are available in the `cpu_adv` plugin; however there is no flag to enable it.  Maybe this should be enabled when using `--full` ?

**Comment by dagwieers** [comment]
Try `--cpu-adv`

**Comment by emotenc** [comment]
The source I pulled from master earlier today does not have that option.  It is not listed in the available options from the cmd line either.  A search of the file brings up no matches.  `--vm-adv` is the only advanced option toggle.

**Comment by dagwieers** [comment]
Feel free to create a pull request to improve the documentation.
