### ISSUE TITLE
Invalid parsing of /proc/<pid>/stat

### ISSUE THREAD

**Issue by xnoreq** [dagwieers/dstat#120]
##### SUMMARY

dstat assumes that the 2nd column in /proc/&lt;pid&gt;/stat cannot contain whitespace, but it does in some cases.

For example:
`cat /proc/4677/stat`
`4677 (tmux: client) S 4676 4677 4677 34816 4677 4194304 306 0 0 0 0 0 0 0 ...`

dstat_top_mem.py uses the 24th column to calculate mem usage:
`usage = int(l[23]) * pagesize`

This works for when the 2nd column contains no space (first column in awk is $1):
`awk '{print $24 " : " $25}' /proc/self/stat`
`711 : 18446744073709551615`

But fails with the above tmux example:
`awk '{print $24 " : " $25}' /proc/4677/stat`
`20017152 : 746`

Tmux is then shown to use 80-90G in dstat --top-mem.
##### ISSUE TYPE
- Bug Report
##### DSTAT VERSION

```
Dstat 0.7.3
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/dstat/

Platform posix/linux2
Kernel 4.7.6-1-ARCH
Python 2.7.12 (default, Jun 28 2016, 08:31:05)
[GCC 6.1.1 20160602]

Terminal type: screen-256color (color support)
Terminal size: 70 lines, 228 columns

Processors: 2
Pagesize: 4096
Clock ticks per secs: 100

internal:
        aio, cpu, cpu-adv, cpu-use, cpu24, disk, disk24, disk24-old, epoch, fs, int, int24, io, ipc, load, lock, mem, mem-adv, net, page, page24, proc, raw, socket, swap, swap-old, sys, tcp, time, udp, unix, vm, vm-adv, zones
/usr/share/dstat:
        battery, battery-remain, condor-queue, cpufreq, dbus, disk-avgqu, disk-avgrq, disk-svctm, disk-tps, disk-util, disk-wait, dstat, dstat-cpu, dstat-ctxt, dstat-mem, fan, freespace, fuse, gpfs, gpfs-ops, helloworld,
        innodb-buffer, innodb-io, innodb-ops, lustre, md-status, memcache-hits, mysql-io, mysql-keys, mysql5-cmds, mysql5-conn, mysql5-innodb, mysql5-innodb-basic, mysql5-innodb-extra, mysql5-io, mysql5-keys, net-packets,
        nfs3, nfs3-ops, nfsd3, nfsd3-ops, nfsd4-ops, nfsstat4, ntp, postfix, power, proc-count, qmail, redis, rpc, rpcd, sendmail, snmp-cpu, snmp-load, snmp-mem, snmp-net, snmp-net-err, snmp-sys, snooze, squid, test, thermal,
        top-bio, top-bio-adv, top-childwait, top-cpu, top-cpu-adv, top-cputime, top-cputime-avg, top-int, top-io, top-io-adv, top-latency, top-latency-avg, top-mem, top-oom, utmp, vm-cpu, vm-mem, vm-mem-adv, vmk-hba, vmk-int,
        vmk-nic, vz-cpu, vz-io, vz-ubc, wifi, zfs-arc, zfs-l2arc, zfs-zil
```

**Comment by xnoreq** [comment]
```
def proc_splitline(filename, sep=None):
    "Return the first line of a file splitted"
#    return open(filename).read().split(sep)
    tmp = linecache.getline(filename, 1).split(sep)
    it = [i for i,c in enumerate(tmp) if c.endswith(')')]
    it = 1 if not it else it[-1]+1
    return tmp[0:1] + [' '.join(tmp[1:it])] + tmp[it:]
#    return linecache.getline(filename, 1).split(sep)
```

**Comment by dagwieers** [comment]
@xnoreq Good catch, although I was hoping to get a cleaner/faster implementation to parse that line.

Also, I have never encountered spaces in the name like tmux on your system. How did you manage to do this ?

**Comment by xnoreq** [comment]
```
$ ps aux|grep 15686
myuser     15686  0.0  0.1  19548  2928 pts/0    Ss+  21:31   0:00 tmux -u new -APD -s main

$ cat /proc/15686/status
Name:   tmux: client
...

$ cat /proc/15686/stat
15686 (tmux: client) S 15...
```

This is also trivial to test with:
```
$ perl -e '$0="this is a test"; <STDIN>' &
[1] 18454

$ cat /proc/18454/status
Name:   this is a test
...
```

**Comment by dagwieers** [comment]
Hmmm, I cannot reproduce this.
```
[dag@moria ~]$ perl -e '$0="this is a test"; <STDIN>' &
[1] 20311
[dag@moria ~]$ cat /proc/20311/stat
20311 (perl) T 20278 20311 20278 34843 20316 1077952512 222 0 0 0 0 0 0 0 20 0 1 0 184965151 125030400 796 18446744073709551615 4194304 4198628 140727883505648 140727883496152 139751640610832 0 0 128 0 1 0 0 17 2 0 0 0 0 0 6295784 6296580 33071104 140727883506763 140727883506800 140727883506800 140727883509738 0
```

And I am running a recent kernel:
```
[dag@moria ~]$ uname -r
4.8.2-1.el6.elrepo.x86_64
```

**Comment by xnoreq** [comment]
So am I. Not sure if this is a difference in kernel config or system configuration.

**Comment by shahn** [comment]
You should be able to reproduce this by just producing a binary with a space and then running it.

**Comment by ecraven** [comment]
I've just had this happen on a server, default arch linux packages. tmux shows as 85G memory :-/

**Comment by o9000** [comment]
Here is a simple way to reproduce:

```
echo -e '#!/bin/bash\necho PID: $$\ncat /proc/$$/stat\nsleep 1000' > 'script .sh'
chmod +x  'script .sh'
./script\ .sh
./script\ .sh
PID: 25603
25603 (script .sh) S 22104 25603 22104 34823 25603 4210688 189 0 0 0 0 0 0 0 20 0 1 0 41549337 18583552 695 18446744073709551615 4194304 5173300 140732546168064 140732546166776 140500374521164 0 65536 4 65538 1 0 0 17 3 0 0 0 0 0 7273968 7310504 38633472 140732546169324 140732546169347 140732546169347 140732546170859 0
...
```

**Comment by o9000** [comment]
Since `/proc/[PID]/stat` is the only type of file that needs this parsing, the method should be used conditionally:

```
    if filename.startswith("/proc/") and filename.endswith("/stat") and filename != "/proc/stat":
        tmp = linecache.getline(filename, 1).split(sep)
        it = [i for i,c in enumerate(tmp) if c.endswith(')')]
        it = 2 if not it else it[-1]+1
        return tmp[0:1] + [' '.join(tmp[1:it])] + tmp[it:]
    else:
        return linecache.getline(filename, 1).split(sep)
```

**Comment by eMPee584** [comment]
.. and I complained to the tmux mailing list why tmux might be using 5 Terabytes of virtual memory :rofl:

**Comment by kaiwan** [comment]
Am facing the same issue w/ firefox reporting 13 TB mem usage (w/ just 4 tabs open)! (was wondering what the heck firefox is upto :-) ).

$ dstat --top-mem
--most-expensive-
  memory process 
We          13.0T
...
$ 

Pl fix this bug!

**Comment by alete89** [comment]
Thanks guys, you helped me to find a bug in another project. =D
https://bitbucket.org/henning/pyqtermwidget/issues/4/bug-parsing-proc-stat

**Comment by eMPee584** [comment]
this patch works very well, never run into a problem with it — thanks @o9000 !
> ```
>     if filename.startswith("/proc/") and filename.endswith("/stat") and filename != "/proc/stat":
>         tmp = linecache.getline(filename, 1).split(sep)
>         it = [i for i,c in enumerate(tmp) if c.endswith(')')]
>         it = 2 if not it else it[-1]+1
>         return tmp[0:1] + [' '.join(tmp[1:it])] + tmp[it:]
>     else:
>         return linecache.getline(filename, 1).split(sep)
> ```
Apart from tmux, firefox also seems affected: https://www.reddit.com/r/firefox/comments/as64ux/firefox_the_browser_that_never_forgets_except/ ..
@dagwieers : how about applying this fix and releasing a new version soonish? :smiley:
