### ISSUE TITLE
Dstat missing last newline when running using a give count, and hiq column is gone

### ISSUE THREAD

**Issue by frippe75** [dagwieers/dstat#123]
##### SUMMARY
CPU header hiq missing as well as last newline when running a fixed amount of samples
I have a script that uses dstat to sample cpu performance on a regular interval using dstat <interval> 2 | tail -1 

After an upgrade to fedora24 (dstat 0.7.2 -> 0.7.3) I got new behaviour.
Seems that the final newline is missing making the tail -1 go blank.

##### ISSUE TYPE
- Bug Report
 

##### DSTAT VERSION
```
Dstat 0.7.3
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/dstat/

Platform posix/linux2
Kernel 4.8.8-200.fc24.x86_64
Python 2.7.12 (default, Sep 29 2016, 13:30:34) 
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)]

Terminal type: xterm-256color (color support)
Terminal size: 60 lines, 211 columns

Processors: 4
Pagesize: 4096
Clock ticks per secs: 100

internal:
	aio, cpu, cpu-adv, cpu-use, cpu24, disk, disk24, disk24-old, epoch, fs, int, int24, io, ipc, load, lock, mem, mem-adv, net, page, page24, proc, raw, socket, swap, swap-old, sys, tcp, time, udp, unix, 
	vm, vm-adv, zones
/usr/share/dstat:
	battery, battery-remain, condor-queue, cpufreq, dbus, disk-avgqu, disk-avgrq, disk-svctm, disk-tps, disk-util, disk-wait, dstat, dstat-cpu, dstat-ctxt, dstat-mem, fan, freespace, fuse, gpfs, gpfs-ops, 
	helloworld, innodb-buffer, innodb-io, innodb-ops, lustre, md-status, memcache-hits, mysql-io, mysql-keys, mysql5-cmds, mysql5-conn, mysql5-innodb, mysql5-innodb-basic, mysql5-innodb-extra, mysql5-io, 
	mysql5-keys, net-packets, nfs3, nfs3-ops, nfsd3, nfsd3-ops, nfsd4-ops, nfsstat4, ntp, postfix, power, proc-count, qmail, redis, rpc, rpcd, sendmail, snmp-cpu, snmp-load, snmp-mem, snmp-net, 
	snmp-net-err, snmp-sys, snooze, squid, test, thermal, top-bio, top-bio-adv, top-childwait, top-cpu, top-cpu-adv, top-cputime, top-cputime-avg, top-int, top-io, top-io-adv, top-latency, top-latency-avg, 
	top-mem, top-oom, utmp, vm-cpu, vm-mem, vm-mem-adv, vmk-hba, vmk-int, vmk-nic, vz-cpu, vz-io, vz-ubc, wifi, zfs-arc, zfs-l2arc, zfs-zil

```

Tests were performed using latest bundled release in fedora24

##### OS / ENVIRONMENT
Running Fedora24 updated today

##### STEPS TO REPRODUCE

[frta@fedora24 ~]$ /usr/bin//dstat --version | grep ^Dstat
Dstat 0.7.3

[frta@fedora24 ~]$ /usr/bin/dstat 1 2 | tail -1
_<< nothing, expected last line of the two lines here >>_

**Checking the ouput without the tail, "works" as expected**
[frta@fedora24 ~]$ /usr/bin/dstat 1 2 
--total-cpu-usage-- -dsk/total- -net/total- ---paging-- ---system--
usr sys idl wai stl| read  writ| recv  send|  in   out | int   csw 
 38   6  56   0   0| 685k  465k|   0     0 | 259k  291k|1536  3982 
 25   3  71   1   0|   0    36k|   0   644B|   0     0 |2362  5420 

**Workaround is to add a third line and tail -2 to get the middle line**
[frta@fedora24 ~]$ /usr/bin//dstat 1 3 | tail -2
 14   2  83   0   0|   0     0 |   0    80B|   0     0 |2026  6070 

**Switching to old 0.7.2 version**
[frta@fedora24 ~]$ ./dstat --version | grep ^Dstat
Dstat 0.7.2

**Works as expected**
[frta@fedora24 ~]$ ./dstat 1 2 | tail -1
 18   2  80   0   0   0|   0     0 |  68B  354B|   0     0 |2105  6114 

**This is the corresponding 0.7.2 listings used above for comparision**
**_Note that column hiq is back. Did not see in the release notes that this was suposed to change_**
[frta@fedora24 ~]$ ./dstat 1 2 
----total-cpu-usage---- -dsk/total- -net/total- ---paging-- ---system--
usr sys idl wai hiq siq| read  writ| recv  send|  in   out | int   csw 
 37   6  56   0   1   1| 685k  465k|   0     0 | 259k  291k|1536  3982 
 26   2  71   0   0   0|   0     0 |   0    80B|   0     0 |2135  4325 
 22   2  75   0   0   0|4096B   48k|   0    80B|4096B    0 |2131  5193 

[frta@fedora24 ~]$ ./dstat 1 3
You did not select any stats, using -cdngy by default.
----total-cpu-usage---- -dsk/total- -net/total- ---paging-- ---system--
usr sys idl wai hiq siq| read  writ| recv  send|  in   out | int   csw 
 37   6  56   0   1   1| 685k  465k|   0     0 | 259k  291k|1536  3983 
 25   1  73   0   0   0|   0     0 |   0   174B|   0     0 |2120  4881 
 20   2  77   0   0   0|8192B  512k|5023B 1862B|4096B    0 |2218  5514 
 22   3  75   0   1   0|4096B  248k|8544B 3305B|   0     0 |2318  4923 

##### EXPECTED RESULTS
That "dstat 1 2 | tail -1" would return the last line  

##### ACTUAL RESULTS
tail -1 gives nothing since the last line seems to miss the newline char.
```
[frta@fedora24 ~]$ /usr/bin//dstat 1 3 | tail -1

```

**Comment by frippe75** [comment]
It's actually an added newline that seems to mess it up.
It seems alot of things changed between versions.

One line more using option "1 1"
`[frta@fedora21 tmp]$ ./dstat_0.7.2 1 1
You did not select any stats, using -cdngy by default.
----total-cpu-usage---- -dsk/total- -net/total- ---paging-- ---system--
usr sys idl wai hiq siq| read  writ| recv  send|  in   out | int   csw 
 10   1  88   0   0   0| 180k  340k|   0     0 |2317B   64k|1172  2668 
 99   0   0   0   0   0|   0   424k|   0     0 |   0     0 |4489  2536 
[frta@fedora21 tmp]$ ./dstat_0.7.3 1 1
You did not select any stats, using -cdngy by default.
--total-cpu-usage-- -dsk/total- -net/total- ---paging-- ---system--
usr sys idl wai stl| read  writ| recv  send|  in   out | int   csw 
 11   1  88   0   0| 180k  340k|   0     0 |2318B   64k|1173  2668 `


Also  terminal ansi escape characters seems to still be there with --noupdate

`[frta@fedora21 tmp]$ ./dstat_0.7.2 1 1
You did not select any stats, using -cdngy by default.
----total-cpu-usage---- -dsk/total- -net/total- ---paging-- ---system--
usr sys idl wai hiq siq| read  writ| recv  send|  in   out | int   csw 
 10   1  88   0   0   0| 180k  340k|   0     0 |2317B   64k|1172  2668 
 99   0   0   0   0   0|   0   424k|   0     0 |   0     0 |4489  2536 
[frta@fedora21 tmp]$ ./dstat_0.7.3 1 1
You did not select any stats, using -cdngy by default.
--total-cpu-usage-- -dsk/total- -net/total- ---paging-- ---system--
usr sys idl wai stl| read  writ| recv  send|  in   out | int   csw 
 11   1  88   0   0| 180k  340k|   0     0 |2318B   64k|1173  2668 `

**Comment by dagwieers** [comment]
- The output of Dstat is not guaranteed to stay the same at all times. It would mean we could not improve the program. Besides it should not matter because the output is intended for humans, not for processing.
- The options `--noupdate` and `--nocolor` indeed do not avoid ANSI output, and maybe it could. If this is important to you, feel free to send a pull request.

**Comment by frippe75** [comment]
Hello Dag!


Thanks for the response!

Ok, maybe should be more clear in the "dstat mission statement". I think most Linux users expect to keep backward compatibility in the output since parsing and piping is in the core of bash scripting. Usually new features/changed behaviour  are added and controlled via new flags. Or a flag to force backward compatibility.

I really like dstat and I think you are limiting you "userbase" with this approach.

Best regards,

Fredrik


________________________________
Från: Dag Wieers <notifications@github.com>
Skickat: den 24 november 2016 00:09
Till: dagwieers/dstat
Kopia: frippe75; Author
Ämne: Re: [dagwieers/dstat] Dstat missing last newline when running using a give count, and hiq column is gone (#123)


  *   The output of Dstat is not guaranteed to stay the same at all times. It would mean we could not improve the program. Besides it should not matter because the output is intended for humans, not for processing.
  *   The options --noupdate and --nocolor indeed do not avoid ANSI output, and maybe it could. If this is important to you, feel free to send a pull request.

-
