### ISSUE TITLE
Problems with "--disk -D total"

### ISSUE THREAD

**Issue by FelixNeutatz** [dagwieers/dstat#126]
##### SUMMARY
We recognized that "--disk -D total" outputs way less than we are expecting from our workload. We also verified that by monitoring the running processes reading from "/proc/[processid]/io". So it turned out that the numbers of "/proc/[processid]/io" don't fit with the numbers of "/proc/diskstats" which is used by "--disk -D total". To further verify that we run:

`./dstat --disk -D total --top-io --top-bio`

"--top-io" reads from  "/proc/[processid]/io". We really see the difference:
![screenshot](https://cloud.githubusercontent.com/assets/5217389/20972668/ee86dc78-bc95-11e6-9f98-eb9d791d5ed5.png)

So my question is: Is this a OS issue similar to [Bug 182251 - Overflow in /proc/diskstats on 64-bit systems](https://bugzilla.redhat.com/show_bug.cgi?id=182251) or something else?

Is there some way to check whether this is really an OS problem or an Dstat problem?

Thank you for your help,
Felix

##### ISSUE TYPE

 - Bug Report ? / Question

##### DSTAT VERSION
```
Dstat 0.7.3
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/dstat/

Platform posix/linux2
Kernel 4.4.3-300.fc23.ppc64
Python 2.7.11 (default, Jul 13 2016, 05:58:03) 
[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)]

Terminal type: xterm (color support)
Terminal size: 41 lines, 144 columns

Processors: 48
Pagesize: 65536
Clock ticks per secs: 100

internal:
	aio, cpu, cpu-adv, cpu-use, cpu24, disk, disk24, disk24-old, epoch, fs, int, int24, io, ipc, load, lock, mem, mem-adv, net, page, 
	page24, proc, raw, socket, swap, swap-old, sys, tcp, time, udp, unix, vm, vm-adv, zones
/home/neutatz/dstat/plugins:
	battery, battery-remain, condor-queue, cpufreq, dbus, disk-avgqu, disk-avgrq, disk-svctm, disk-tps, disk-util, disk-wait, dstat, 
	dstat-cpu, dstat-ctxt, dstat-mem, fan, freespace, fuse, gpfs, gpfs-ops, helloworld, ib, innodb-buffer, innodb-io, innodb-ops, 
	jvm-full, jvm-vm, lustre, md-status, memcache-hits, mongodb-conn, mongodb-mem, mongodb-opcount, mongodb-queue, mongodb-stats, 
	mysql-io, mysql-keys, mysql5-cmds, mysql5-conn, mysql5-innodb, mysql5-innodb-basic, mysql5-innodb-extra, mysql5-io, mysql5-keys, 
	net-packets, nfs3, nfs3-ops, nfsd3, nfsd3-ops, nfsd4-ops, nfsstat4, ntp, postfix, power, proc-count, qmail, redis, rpc, rpcd, 
	sendmail, snmp-cpu, snmp-load, snmp-mem, snmp-net, snmp-net-err, snmp-sys, snooze, squid, test, thermal, top-bio, top-bio-adv, 
	top-childwait, top-cpu, top-cpu-adv, top-cputime, top-cputime-avg, top-int, top-io, top-io-adv, top-latency, top-latency-avg, top-mem, 
	top-oom, utmp, vm-cpu, vm-mem, vm-mem-adv, vmk-hba, vmk-int, vmk-nic, vz-cpu, vz-io, vz-ubc, wifi, zfs-arc, zfs-l2arc, zfs-zil

```

##### OS / ENVIRONMENT
Kernel:
Linux 4.4.3-300.fc23.ppc64 #1 SMP Tue Mar 1 06:23:07 UTC 2016 ppc64 ppc64 ppc64 GNU/Linux

OS:
Fedora release 23 (Twenty Three)

**Comment by dagwieers** [comment]
The numbers look fine. You have to consider I/O going to disk. Not other I/O (piped, network, pagecache). And they should compare roughly. Take measurements over a longer period (e.g. 1 minute) and compare -d with --top-bio. I/O should be comparable, but may be shifted a bit due to delayed writes.

**Comment by FelixNeutatz** [comment]
Thanks for the quick update. I run it again and the cumulative charts are the following:

cumulative chart of --disk -D total             |  cumulative chart of --top-io             |  cumulative chart of --top-bio             
:-------------------------:|:-------------------------:|:-------------------------:
![cum_agg_chart_dsk_total_read](https://cloud.githubusercontent.com/assets/5217389/21067767/b935717c-be6d-11e6-83dc-b02775308de7.png) |  ![cum_agg_chart_most_expensive_io process](https://cloud.githubusercontent.com/assets/5217389/21067771/c489f976-be6d-11e6-8981-bd104fac34c2.png)  |   ![cum_agg_chart_most_expensive_block io process](https://cloud.githubusercontent.com/assets/5217389/21067790/d9fecd36-be6d-11e6-87bb-c26f11bab56d.png)

So  --top-io is way more than both other metrics

**Comment by dagwieers** [comment]
Right, because --top-io is **NOT** block I/O. As I told you, it includes a lot of other things that are not related to disks. So you are comparing apples and oranges...
And the difference between --disk and --top-bio is related to:
1. buffering, process metrics are real-time, but disk I/O is buffered
2. --top-bio metrics only includes block I/O from a single process where --disk metrics include all disk related I/O, so that's going to be different. Besides block I/O is related to filesystem block-sizes where applications may not have those boundaries.
