### ISSUE TITLE
Allow show network usage in kilobits instead of kilobytes

### ISSUE THREAD

**Issue by theundefined** [dagwieers/dstat#131]
##### SUMMARY
Currently dstat show network usage in bytes/kilobytes/megabytes. It's not very useful in "it" world, where network traffic is always counted in bits/kilobit/megabit. 
it would be usefull to allow change (by option?) show values to bits instead of bytes.

##### ISSUE TYPE
 - Feature Idea

##### DSTAT VERSION
```
Dstat 0.7.2
```

**Comment by dagwieers** [comment]
There is an option `--bits` already.

**Comment by scottchiefbaker** [comment]
I personally wrote `--bits` because bytes/sec for bandwdith doesn't make any sense.

**Comment by theundefined** [comment]
ok.. sorry :) I didn't check latest version :-D
