### ISSUE TITLE
Feature request : Total Bytes cumulated on delay X

### ISSUE THREAD

**Issue by neooblaster** [dagwieers/dstat#150]
Hi dstat team,

First, I checked if that feature request has not been done yet.
I did not found results corresponding to my need.

I found that tool awesome, very complete, flexible, colorfull.
The only one feature I found is missing : total bytes cummulated.
Indeed, you offer the option `total` (`-D`, `-N`) that count bytes for all devices (Disk / Net Interface) at **time T**.

Given you offer options `[delay [count]]`, the capability to really count total bytes processed during the delay `x` is more revelant than total of devices as like without delay.

Maybe is it a bug ? If it is, I will send all necessary informations requested.

Thanks for your reply and for dstat tool !

Regards,
Nicolas DUPRE.

**Comment by dagwieers** [comment]
Writing your own module to do this is quite easy, but it's not a bug and nobody requested it in the past 15 years that I know of.

**Comment by neooblaster** [comment]
If I could, I will, but I'm comfortable with Python language and Linux package integration, but I thought about it ;)

Do you think you can help me in by guiding me in main lines (steps to realize it) ?

Currently, I you have not really enough time to do this, but I'd try.

If I succeeded, I will sent you a PR.

**Comment by zwieberl** [comment]
Just to add a voice here: This is exactly what I would love to have as well!
