### ISSUE TITLE
MariaDB modules

### ISSUE THREAD

**Issue by ottok** [dagwieers/dstat#158]
Hello!

Dstat currently has a number of mysql-* and innodb-* modules. As a MariaDB fan I'd like to use the name 'mariadb' in the commands. If I make a pull request to rename and alias these, so that both names work, will it be accepted?

After the rename my plan is to extend the modules a bit, so that the mysqld-process authentication (both for MariaDB and MySQL servers) is more robust in the first place, and more user friendly if the database credentials don't work or the user does not have the required permissions.

After that step I'll add some modules to get some more info from MariaDB using modern performance counters.

**Comment by scottchiefbaker** [comment]
I don't want to speak for @dagwieers but as another person with commit access on this repo I'd be fine with this. If the long term goal is keep MySQL as it is, and to add features specific to MariaDB then I think it sounds great.

**Comment by ottok** [comment]
I already found in the pull requests a huge improvement to current affairs: https://github.com/dagwieers/dstat/pull/96

Once that is merged I can fix the other details. Basically I was thinking of doing much of the same that has already been sitting in a PR for 3 years.

Thanks for replying @scottchiefbaker and letting the world know this project is not completely dead. :smile:

**Comment by scottchiefbaker** [comment]
Sounds good to me... I'm just a helper (my Python isn't real strong), but @dagwieers should be able to get things rolling.
