### ISSUE TITLE
dstat --thermal fails but acpi support is present

### ISSUE THREAD

**Issue by eugenio** [dagwieers/dstat#18]
As from title dstat --thermal fails to run with message "Module dstat_thermal failed to load. (Needs kernel ACPI or IBM-ACPI support)." but as i say in title acpi support is present and working because I run dstat --battery (wich I read requires acpi too) and it worked just fine. My machine is an asus n35sv with 2nd gen sandy bridge running ubuntu 11.10 with all latest updates and kernel. Let me know if you need other info (please provide commands to run as I'm newbie on and I know only a few of them).

Edit:
 I found out that cat /proc/acpi/thermal_zone/THM0/temperature is deprecated, /sys/bus/acpi/devices/LNXTHERM\:00/thermal_zone/temp should be used instead. I might be mistaken but I tried  cat with the second path on my system and it worked.  I'm not a python programmer nor a linux expert so I wouldn't dare if not asked to try to patch the file but at least I found a workaround so that a willing expert or a mantainer could. 
The discussion where I found the right path is : http://www.linuxquestions.org/questions/programming-9/how-to-get-cpu-temperature-in-linux-598658/

Edit2

I worked out a solution by myself. I forked the project and committed a new version of the file to my fork. I'll wait for someone to review it and merge it with the original branch if ok.

**Comment by dagwieers** [comment]
Pull-request #88 implements a solution. Please test and provide feedback on #88.
I am going to close this issue.
