### ISSUE TITLE
Use non-deprecated paths for battery stuff

### ISSUE THREAD

**Issue by svenstaro** [dagwieers/dstat#24]
--battery and --power fail due to "Module dstat_power failed to load. ([Errno 2] No such file or directory: '/proc/acpi/battery/')" which sucks since this dir is /sys/class/power_supply/BAT1 in modern Linux systems.

**Comment by q2dg** [comment]
I have dstat 0.7.3 installed from official packages in Fedora 26 and I still suffer this error.
I've seen https://github.com/dagwieers/dstat/blob/master/ChangeLog and this pull request isn't listed on it.
Please, it's really annoying
