### ISSUE TITLE
Reverse colors between green and red?

### ISSUE THREAD

**Issue by wting** [dagwieers/dstat#38]
I prefer green for low usage / idle, and red for high usage which is the opposite of the current behavior (e.g. cpu usage, cpu frequency, disk throughput). Is it possible to switch color behavior?

**Comment by chrcoluk** [comment]
I would like to replace the blue colours with something like green or yellow as on a black background its barely readable.

**Comment by dagwieers** [comment]
@chrcoluk The obvious way to make blue more readable is configuring your terminal to display a lighter blue than what is configured. This helps not just for Dstat, but also for other tools using blue.

**Comment by zviratko** [comment]
Just came here to open a bug and found this issue

When it comes to CPU load, interpretation of red=bad or green=good is of course dependant on what one expects - if I wanted to run computations then 0% CPU usage would in fact be bad.
But when it comes to disk statistics for example, surely 100% disk utilization should be in red by default and not green - one might argue it's the same thing, but for 99% people using dstat red would be much more intuitive (and 100% disk utilization usually _is_ bad, except special scenarios.)
