### ISSUE TITLE
wifi stats are ignored on raspberry pi

### ISSUE THREAD

**Issue by kumar303** [dagwieers/dstat#42]
Hello.
I'd like to use ``--wifi`` on a raspberry pi with a [tenda N150 dongle](https://www.modmypi.com/tenda-wireless-n150-usb-network-adapter) but the values are always:

```
|lnk s/n
| -   -
```
I went into the source and removed the ``qual.noiselevel == -256`` check from this line of the dstat_wifi plugin:
```
if qual.quality == 0 or qual.signallevel == -101 or qual.noiselevel == -101 or qual.signallevel == -256 or qual.noiselevel == -256:
```
to read:
```
if qual.quality == 0 or qual.signallevel == -101 or qual.noiselevel == -101 or qual.signallevel == -256:
```
and it begun to show my link and signal levels as expected.

Why is a noise level of -256 always ignored? I don't know what this means but I guess my specific dongle always has a value of -256.

I could make a new plugin as a workaround but I was curious about it.

**Comment by scottchiefbaker** [comment]
@kumar303 any luck on that pull request? I'm curious about DB levels on the pi also.

Which wifi adapter do you have specifically?

**Comment by kumar303** [comment]
I was using a tenda N150 wifi dongle but I guess I never made a pull request. You can see my patch in the original comment if you need it though.

**Comment by scottchiefbaker** [comment]
@kumar303 is this patch still required on the 4.x kernel that the pi is running now? Are you still seeing -256, that almost sounds like a driver thing to me that might have been fixed already? I don't have that module to test.

**Comment by kumar303** [comment]
I have no idea. It's been over 3 years since I filed it. If no one else has
run into it, I suggest closing the issue.

**Comment by scottchiefbaker** [comment]
Closing for agedness unless we run in to something like this in the future.
