### ISSUE TITLE
Two or one column per cpu stat

### ISSUE THREAD

**Issue by do11** [dagwieers/dstat#53]
Modern server frequently have many CPUs so detailed output of dstat for cpu become very long and don't fit into the screen, being that it gets "trimmed" i.e. deleted.

I request feature to make shorter all-cpu output, which should show only cpu load per cpu. So instead of 7 columns per cpu 'usr sys idl wai hiq siq stl' it will be just one, which should be sum of (usr sys wai hiq siq stl) or just (100 - idle). Such way it will be possible to see 7 times more cpus than now.

Additional useful improvement to that would be to show two column per cpu: load and iowait time. Load should be sum of (usr sys hiq siq stl) and iowait is wai (as I understand). That would be useful to see if cpu is actually crunching.

**Comment by dagwieers** [comment]
I am closing this issue as Dstat v0.7.3 includes the `--cpu-use` option to do just this.
Thanks for the feedback !
