### ISSUE TITLE
Should Dstat CSV output actually be semicolon or comma separated ?

### ISSUE THREAD

**Issue by dagwieers** [dagwieers/dstat#59]
Currently we use a comma as separator for the CSV output, and when implementing I thought that made most sense. However a semicolon is less common to be used inside the output/string as a comma.

Besides a comma is used in Europa as a radix point, rather than the dot. And therefore the default separator used by Excel/LibreOffice is configured to be a semicolon.

What do you think ?

Changing might have impact to people already processing it with a comma.

**Comment by thinrope** [comment]
comma by default is fine, configurable is even better (like cut/paste commands)
--delimeter ";" ("," is the default)
