### ISSUE TITLE
Could dstat add swap in/out feature?

### ISSUE THREAD

**Issue by leafonsword** [dagwieers/dstat#80]
vmstat's swap in/out feature is very helpful in IO hang situation,could dstat also add this feature?

**Comment by dagwieers** [comment]
We have a `page` plugin shows a system's page-in and page-out activity. Is this what you are looking for ? Or is this related to VMware counters ?

**Comment by leafonsword** [comment]
@dagwieers  
thx，page and swap are often interchangable
