### ISSUE TITLE
no adv plugins

### ISSUE THREAD

**Issue by Paul17041993** [dagwieers/dstat#91]
I recently installed dstat on a cent 6.6 server in an attempt to find what processes are taking up the IO on the box, however I _need_ the PIDs and not the names, because the only results will be 'java' as that's what all the servers run off. The -adv plugins should have the PIDs, except none of them exist in the install and I cant find anything at all about them other then they should exist...

**Comment by dagwieers** [comment]
@Paul17041993 We just released 0.7.3 which include these -adv plugins. Let us know if you have any issues.
