### ISSUE TITLE
dstat_net filtering out interfaces with 0 packets

### ISSUE THREAD

**Issue by trittweiler** [dagwieers/dstat#94]
Howdy,

The 'discover' method of dstat_net looks as follows:

``` python
    def discover(self, *objlist):
        ret = []
        for l in self.splitlines(replace=':'):
            if len(l) < 17: continue
            if l[2] == '0' and l[10] == '0': continue
            name = l[0]
            if name not in ('lo', 'face'):
                ret.append(name)
        ret.sort()
        for item in objlist: ret.append(item)
        return ret
```

The l[2] corresponds to the number of received packets, and l[10] to the number of transmitted packets.

I wonder what the reason might be for filtering out interfaces that have not received or transmitted a packet yet?

We use dstat to dump to a log file at system start up at which point the counters for the interfaces, that we want to monitor, are still 0. With the current code, dstat_net would just skip these interfaces at its initialization time, and it would not actually monitor them.

Thanks in advance, and many thanks indeed for dstat :)

Tobias

**Comment by dagwieers** [comment]
This was obviously done on purpose, but there is a use-case to control this. I would suggest we make a design of the options we would like to include to influence what items we want to include. Currently you have `-f` or `--full` to give access to all (non-zero) items, and we have switches to select specific items (e.g. `-C total`, `-D sda,sdb`, `-N eth0,eth1`).

I would go for an additional option, either to influence the selection for `-f` / `--full` or one that overrides `-f` / `--full`. It depends on backward compatibility and/or easy-of-use.
